# Generated by Django 2.2.17 on 2020-12-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_auto_20200903_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=100)),
                ('L_name', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('Objective', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='')),
                ('Email', models.EmailField(max_length=254)),
                ('Tel_no', models.CharField(max_length=10)),
                ('Addr_1', models.CharField(max_length=250)),
                ('Addr_2', models.CharField(max_length=250)),
                ('Country', models.CharField(max_length=50)),
                ('Zipcode', models.CharField(max_length=6)),
                ('Other', models.CharField(max_length=1000)),
                ('skills', models.CharField(max_length=500)),
            ],
        ),
    ]
