# Generated by Django 2.2.17 on 2020-12-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
