# Generated by Django 2.2.17 on 2020-12-26 08:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0006_auto_20201226_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Other',
        ),
        migrations.AlterField(
            model_name='data',
            name='edu',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='exp',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
