# Generated by Django 3.0 on 2021-04-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0008_auto_20201226_0844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='UserData',
        ),
    ]
