# Generated by Django 3.0 on 2021-04-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0009_auto_20210417_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
